### ISSUE TITLE
Handsontable is not MIT-licensed anymore

### ISSUE THREAD

**Issue by GerardSmit** [krzysztofspilka/JSpreadsheets#17]
In their latest release they replaced the MIT license to source-available.

Quoted from the last release (https://github.com/handsontable/handsontable/releases/tag/7.0.0):

> Handsontable is now "source-available" instead of "open source". The MIT license has been replaced with custom, free for non-commercial license.

For more information see https://github.com/handsontable/handsontable/issues/5831.

**Comment by marclaporte** [comment]
Seems it has been updated:
https://github.com/krzysztofspilka/JSpreadsheets/commit/aeb89150a174a0d9d38c958d31936a4d628e2f4b#diff-a2feef7cfa8a4832fab8c292d7e0eda1R6

Can we close?
