### ISSUE TITLE
Angular-Slickgrid no longer showing up on the website

### ISSUE THREAD

**Issue by ghiscoding** [krzysztofspilka/JSpreadsheets#20]
Hello, I created a PR few months ago t add Angular-Slickgrid (which I'm the author) to the website and it worked for some time but is no longer showing. Not sure why though.

Here is the `md` [file](https://github.com/krzysztofspilka/JSpreadsheets/blob/master/source/projects/angular-slickgrid.md) for it

**Comment by budnix** [comment]
Thanks for spotting this! Indeed there was an issue related to grabbing the wrong commit from the master branch to build a list of the libraries (in that commit Angular Slickgrid did not exist). It is back to live (https://jspreadsheets.com/angular-slickgrid.html).
